# Generated by Django 3.0.5 on 2021-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_auto_20210615_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='transfer',
            field=models.IntegerField(max_length=50),
        ),
    ]
